apiVersion: v1
kind: Service
metadata:
  name: temporal-ui
  namespace: temporal
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: temporal-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: temporal-ui
  name: temporal-ui
  namespace: temporal
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: temporal-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: temporal-ui
    spec:
      containers:
      - env:
        - name: TEMPORAL_ADDRESS
          value: temporal.<namespace>.cluster.local:7233
        - name: TEMPORAL_UI_PORT
          value: "8080"
        - name: TEMPORAL_UI_PUBLIC_PATH
          value: "/temporal-ui"
        - name: TEMPORAL_UI_ENABLED
          value: "true"
        - name: VISIBILITY_DBNAME
          value: temporal_visibility
        image: temporalio/ui:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        readinessProbe:
          exec:
            command:
            - ls
            - /
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1        
        livenessProbe:
          exec:
            command:
            - ls
            - /
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: temporal-ui
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30